# Generated by Django 3.1.5 on 2021-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=50, verbose_name='سایز محصول')),
                ('product_unit', models.CharField(max_length=50, verbose_name='واحد سایز')),
            ],
            options={
                'verbose_name': 'سایز محصول',
                'verbose_name_plural': 'سایز محصول ها',
            },
        ),
    ]
