# Generated by Django 3.1.5 on 2021-02-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditails_product', '0002_auto_20210225_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(max_length=50, verbose_name='برند محصول')),
            ],
            options={
                'verbose_name': 'برند محصول',
                'verbose_name_plural': 'برند محصولات',
            },
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_classify', models.CharField(max_length=50, verbose_name='نوع محصول')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'نوع محصولات',
            },
        ),
    ]
