# Generated by Django 3.1.5 on 2021-02-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ditails_product', '0003_brand_type'),
    ]

