# Generated by Django 3.1.5 on 2021-02-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0021_auto_20210225_1626'),
        ('ditails_product', '0004_auto_20210225_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='type',
        ),
    ]
