# Generated by Django 3.1.5 on 2021-03-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditails_product', '0005_delete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='product_color_english',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ محصول به انگلیسی'),
        ),
    ]
