# Generated by Django 3.1.5 on 2021-02-25 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tag_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=20, verbose_name='نام تگ')),
                ('product_date', models.DateTimeField(default=datetime.datetime(2021, 2, 25, 11, 16, 33, 975871), verbose_name='تاریخ تگ')),
                ('product_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال بودن تگ')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'مدل تگ',
                'verbose_name_plural': 'مدل های تگ',
            },
        ),
    ]
