# Generated by Django 3.1.5 on 2021-02-25 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_product',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 11, 17, 16, 641311), verbose_name='تاریخ تگ'),
        ),
    ]
