# Generated by Django 3.1.5 on 2021-02-25 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_shop', '0016_auto_20210225_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_product',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 22, 20, 44, 53467), verbose_name='تاریخ تگ'),
        ),
    ]
