# Generated by Django 3.1.5 on 2021-02-27 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_shop', '0036_auto_20210227_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_product',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 21, 34, 14, 366843), verbose_name='تاریخ تگ'),
        ),
    ]
