# Generated by Django 3.1.5 on 2021-03-01 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_shop', '0039_auto_20210228_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_product',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 13, 47, 52, 858732), verbose_name='تاریخ تگ'),
        ),
    ]
