# Generated by Django 3.1.5 on 2021-03-01 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_shop', '0043_auto_20210301_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_product',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 13, 51, 3, 539638), verbose_name='تاریخ تگ'),
        ),
    ]
