# Generated by Django 3.1.5 on 2021-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=90, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل شرکت')),
                ('subject', models.CharField(max_length=90, verbose_name='موضوع')),
                ('massege', models.TextField(verbose_name='پیغام')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس  ها',
            },
        ),
        migrations.CreateModel(
            name='sitesetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='ادرس شرکت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل شرکت')),
                ('phone', models.IntegerField(verbose_name='تلفن شرکت')),
                ('google_locution', models.URLField(verbose_name='مکان در نقشه')),
                ('instagrame_address', models.URLField(verbose_name='ادرس اینستاگرام')),
                ('logo_image', models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='logo', verbose_name='عکس لوگو')),
                ('telegrame_address', models.URLField(verbose_name='ادرس تلگرام ')),
                ('aparat_address', models.URLField(verbose_name='ادرس اپارات')),
                ('twitter_address', models.URLField(verbose_name='ادرس تویتر')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
