# Generated by Django 3.1.5 on 2021-02-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل '),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='aparat_address',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس اپارات'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagrame_address',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='telegrame_address',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس تلگرام '),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='twitter_address',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس تویتر'),
        ),
    ]
