# Generated by Django 3.1.5 on 2021-02-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_auto_20210219_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='google_locution',
            field=models.TextField(verbose_name='مکان در نقشه'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(max_length=90, verbose_name='تلفن شرکت'),
        ),
    ]
