# Generated by Django 3.1.5 on 2021-04-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0004_auto_20210220_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_text', models.TextField(verbose_name='توضیح حریم خصوصی ')),
            ],
            options={
                'verbose_name': 'حریم خصوصی',
                'verbose_name_plural': 'حریم خصوصی',
            },
        ),
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_text', models.TextField(verbose_name='توضیح شرایط و قوانین ')),
            ],
            options={
                'verbose_name': 'شرایط و قوانین',
                'verbose_name_plural': 'شرایط و قوانین',
            },
        ),
    ]
