# Generated by Django 3.1.5 on 2021-02-28 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0030_auto_20210228_2005'),
        ('comment_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Product_shop.product_shop'),
            preserve_default=False,
        ),
    ]
