# Generated by Django 3.1.5 on 2021-03-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_product', '0003_auto_20210301_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='product_id',
        ),

    ]
