# Generated by Django 3.1.5 on 2021-03-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='seasion_title2',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='متن دلخواه برای اسلایدر'),
        ),
    ]
