# Generated by Django 3.1.5 on 2021-03-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slider_seasion_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='seasion_title2',
        ),
    ]
