# Generated by Django 3.1.5 on 2021-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_remove_slider_seasion_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slider_image1_url',
            field=models.URLField(default='', verbose_name='Url کالکشن 1 '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='slider_image2_url',
            field=models.URLField(default='', verbose_name='Url کالکشن 2 '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='slider_image3_url',
            field=models.URLField(default='', verbose_name='Url کالکشن 3 '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='slider_image4_url',
            field=models.URLField(default='', verbose_name='Url کالکشن 4 '),
            preserve_default=False,
        ),
    ]
