# Generated by Django 3.1.5 on 2021-02-25 07:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product_shop', '0009_auto_20210225_1055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_date', models.DateTimeField(default=datetime.datetime(2021, 2, 25, 10, 55, 47, 843783), verbose_name='تاریخ سفارش')),
                ('is_paid', models.BooleanField(default=False, verbose_name=' سفارش پرداخت شده / نشده')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id کاربر')),
            ],
            options={
                'verbose_name': 'صبد خرید',
                'verbose_name_plural': 'صبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='order_ditails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_shop.product_shop')),
            ],
            options={
                'verbose_name': ' جزئیات صبد خرید',
                'verbose_name_plural': 'جزئیات صبدهای خرید',
            },
        ),
    ]
