# Generated by Django 3.1.5 on 2021-02-25 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_auto_20210225_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 11, 17, 16, 652312), verbose_name='تاریخ سفارش'),
        ),
    ]
