# Generated by Django 3.1.5 on 2021-02-25 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0016_auto_20210225_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 16, 36, 32, 224477), verbose_name='تاریخ سفارش'),
        ),
    ]
