# Generated by Django 3.1.5 on 2021-02-26 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0025_auto_20210225_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 18, 17, 59, 445609), verbose_name='تاریخ سفارش'),
        ),
    ]
