# Generated by Django 3.1.5 on 2021-02-26 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0026_auto_20210226_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 18, 24, 47, 933780), verbose_name='تاریخ سفارش'),
        ),
    ]
