# Generated by Django 3.1.5 on 2021-02-27 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0036_auto_20210227_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 14, 51, 20, 862717), verbose_name='تاریخ سفارش'),
        ),
    ]
