# Generated by Django 3.1.5 on 2021-03-03 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0053_auto_20210303_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='finally_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=90, verbose_name='نام نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل ')),
                ('phone', models.CharField(max_length=90, verbose_name='تلفن ')),
                ('address', models.TextField(verbose_name='ادرس ')),
                ('post_code', models.CharField(max_length=90, verbose_name='کد پستی')),
                ('city', models.CharField(max_length=90, verbose_name='شهر و استان')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 16, 35, 11, 745713), verbose_name='تاریخ سفارش'),
        ),
    ]
