# Generated by Django 3.1.5 on 2021-03-04 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0056_auto_20210304_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 12, 21, 47, 542859), verbose_name='تاریخ سفارش'),
        ),
    ]
