# Generated by Django 3.1.5 on 2021-04-07 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0059_auto_20210319_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 15, 32, 19, 39028), verbose_name='تاریخ سفارش'),
        ),
    ]
