# Generated by Django 3.1.5 on 2021-04-07 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_prducts', '0003_auto_20210319_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 15, 32, 19, 58029), verbose_name='تاریخ '),
        ),
    ]
