# Generated by Django 3.1.5 on 2021-02-24 11:05

import colorfield.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ditails_product', '0001_initial'),
        ('tag_shop', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان دسته بندی')),
                ('name', models.CharField(max_length=80, verbose_name='نام دسته بندی در url')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='product_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Gender', models.CharField(choices=[('woman', 'زن'), ('man', 'مرد'), ('kids', 'بجه')], default='S', max_length=10, verbose_name='محصول مربوط با ')),
                ('product_name', models.CharField(max_length=80, verbose_name='نام محصول')),
                ('product_description', models.TextField(null=True, verbose_name='توضیحات محصول')),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='قیمت محصول')),
                ('product_count', models.IntegerField(default=0, verbose_name='تعداد محصول')),
                ('product_brand', models.CharField(default='متفرقه', max_length=80, verbose_name='برند محصول')),
                ('product_type', models.CharField(choices=[('simple', 'ساده'), ('discount', 'تخفیف'), ('new', 'جدبد')], default='S', max_length=10, verbose_name='مدل محصول')),
                ('price_discount', models.IntegerField(default=0, verbose_name='درصد تخفیف محصول')),
                ('product_color1', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='رنگ 1 محصول')),
                ('product_image', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='product_shop', verbose_name='عکس محصول')),
                ('product_date', models.DateTimeField(default=datetime.datetime(2021, 2, 24, 14, 35, 56, 666017), verbose_name='تاریخ محصول')),
                ('product_visit', models.IntegerField(default=0, editable=False, verbose_name='تعداد بازدید محصول')),
                ('product_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال بودن محصول')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('collect_products', models.ManyToManyField(to='Product_shop.collect_product', verbose_name='دسته بندی')),
                ('product_size', models.ManyToManyField(to='ditails_product.size', verbose_name='سایز محصول')),
                ('tag_products', models.ManyToManyField(to='tag_shop.tag_product', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'فروشگاه محصول',
                'verbose_name_plural': 'فروشگاه محصولات ',
            },
        ),
        migrations.CreateModel(
            name='product_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان محصول')),
                ('image', models.ImageField(blank=True, default='defult.jpg', null=True, upload_to='product_shop/product_gallery', verbose_name='عکس های محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_shop.product_shop')),
            ],
            options={
                'verbose_name': 'گالری عکس',
                'verbose_name_plural': 'گالری عکس ها',
            },
        ),
    ]
