# Generated by Django 3.1.5 on 2021-02-24 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 14, 37, 54, 27626), verbose_name='تاریخ محصول'),
        ),
    ]
