# Generated by Django 3.1.5 on 2021-02-24 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0002_auto_20210224_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 14, 53, 15, 237449), verbose_name='تاریخ محصول'),
        ),
    ]
