# Generated by Django 3.1.5 on 2021-02-24 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0004_auto_20210224_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 0, 21, 596636), verbose_name='تاریخ محصول'),
        ),
    ]
