# Generated by Django 3.1.5 on 2021-02-25 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0005_auto_20210224_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 10, 46, 56, 878413), verbose_name='تاریخ محصول'),
        ),
    ]
