# Generated by Django 3.1.5 on 2021-02-25 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0010_auto_20210225_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 11, 3, 29, 804015), verbose_name='تاریخ محصول'),
        ),
    ]
