# Generated by Django 3.1.5 on 2021-02-25 10:17

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0013_auto_20210225_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_color1',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='رنگ خاص محصول'),
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 13, 47, 2, 742436), verbose_name='تاریخ محصول'),
        ),
    ]
