# Generated by Django 3.1.5 on 2021-02-25 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ditails_product', '0002_auto_20210225_1347'),
        ('Product_shop', '0014_auto_20210225_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_shop',
            name='product_color',
            field=models.ManyToManyField(to='ditails_product.color', verbose_name='رنگ محصول'),
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 13, 47, 36, 222351), verbose_name='تاریخ محصول'),
        ),
    ]
