# Generated by Django 3.1.5 on 2021-02-25 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ditails_product', '0003_brand_type'),
        ('Product_shop', '0016_auto_20210225_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_shop',
            name='product_classify',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='ditails_product.type', verbose_name='نوع محصول'),
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditails_product.brand', verbose_name='برند محصول'),
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 15, 49, 26, 86638), verbose_name='تاریخ محصول'),
        ),
    ]
