# Generated by Django 3.1.5 on 2021-02-25 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ditails_product', '0003_brand_type'),
        ('Product_shop', '0017_auto_20210225_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ditails_product.type', verbose_name='نوع محصول'),
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 15, 50, 52, 231565), verbose_name='تاریخ محصول'),
        ),
    ]
