# Generated by Django 3.1.5 on 2021-02-25 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ditails_product', '0004_auto_20210225_1555'),
        ('Product_shop', '0018_auto_20210225_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ditails_product.type', verbose_name='نوع محصول'),
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 15, 55, 46, 147376), verbose_name='تاریخ محصول'),
        ),
    ]
