# Generated by Django 3.1.5 on 2021-02-25 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0019_auto_20210225_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 15, 56, 24, 384563), verbose_name='تاریخ محصول'),
        ),
    ]
