# Generated by Django 3.1.5 on 2021-02-25 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0020_auto_20210225_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_shop',
            name='product_classify',
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 16, 26, 54, 379857), verbose_name='تاریخ محصول'),
        ),
    ]
