# Generated by Django 3.1.5 on 2021-02-26 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect_product', '0001_initial'),
        ('Product_shop', '0022_auto_20210226_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_shop',
            name='xxxxxxxxx',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='collect_product.collect_product_type', verbose_name='صول'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 18, 56, 45, 548462), verbose_name='تاریخ محصول'),
        ),
    ]
