# Generated by Django 3.1.5 on 2021-02-26 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0023_auto_20210226_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_shop',
            name='collect_products',
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 19, 28, 13, 795330), verbose_name='تاریخ محصول'),
        ),
        migrations.DeleteModel(
            name='collect_product',
        ),
    ]
