# Generated by Django 3.1.5 on 2021-02-27 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0025_auto_20210226_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='collect_products',
            field=models.ManyToManyField(blank=True, null=True, to='Product_shop.collect_product', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 14, 49, 58, 31979), verbose_name='تاریخ محصول'),
        ),
    ]
