# Generated by Django 3.1.5 on 2021-02-27 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect_product', '0001_initial'),
        ('Product_shop', '0026_auto_20210227_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_shop',
            name='main_collect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='collect_product.collect_product_main', verbose_name='محصول'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 14, 51, 20, 849716), verbose_name='تاریخ محصول'),
        ),
    ]
