# Generated by Django 3.1.5 on 2021-02-28 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0028_auto_20210227_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 19, 46, 20, 678291), verbose_name='تاریخ محصول'),
        ),
    ]
