# Generated by Django 3.1.5 on 2021-02-28 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0029_auto_20210228_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 20, 5, 38, 615522), verbose_name='تاریخ محصول'),
        ),
    ]
