# Generated by Django 3.1.5 on 2021-03-03 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0041_auto_20210303_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 13, 54, 12, 251943), verbose_name='تاریخ محصول'),
        ),
    ]
