# Generated by Django 3.1.5 on 2021-03-03 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_shop', '0042_auto_20210303_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 16, 7, 0, 661096), verbose_name='تاریخ محصول'),
        ),
    ]
