# Generated by Django 3.1.5 on 2021-03-19 12:57

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Product_shop', '0048_auto_20210304_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_shop',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 16, 27, 48, 254734), verbose_name='تاریخ محصول'),
        ),
        migrations.AlterField(
            model_name='product_shop',
            name='product_price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=20, verbose_name='قیمت محصول'),
        ),
    ]
