# Generated by Django 3.1.5 on 2021-02-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collect_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_collect_product', models.CharField(max_length=80, verbose_name='عنوان دسته بندی')),
                ('name_collect_product', models.CharField(max_length=80, verbose_name='نام دسته بندی در url')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='collect_product_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_collect_product_main', models.CharField(max_length=80, verbose_name='عنوان دسته بندی')),
                ('name_collect_product_main', models.CharField(max_length=80, verbose_name='نام دسته بندی در url')),
            ],
            options={
                'verbose_name': 'دسته بندی کلی  محصول',
                'verbose_name_plural': 'دسته بندی کلی محصولات',
            },
        ),
        migrations.CreateModel(
            name='collect_product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_collect_product_type', models.CharField(max_length=80, verbose_name='عنوان ')),
                ('name_collect_product_type', models.CharField(max_length=80, verbose_name='نام عنوان در url')),
                ('details_collect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect_product.collect_product')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'عنوان محصولات',
            },
        ),
        migrations.AddField(
            model_name='collect_product',
            name='details_collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect_product.collect_product_main'),
        ),
    ]
